apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus-project
  namespace: argocd
spec:
  description: Project for prometheus app
  sourceRepos:
  - 'https://prometheus-community.github.io/helm-charts'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: 'kube-system'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'