kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gwkc-1
nodes:
- role: control-plane
  kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            # Taint the control plane node to prevent workload scheduling
            register-with-taints: "node-role.kubernetes.io/control-plane=:NoSchedule"
- role: worker
- role: worker
- role: worker