kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gwkc-1
nodes:
- role: control-plane
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   listenAddress: "0.0.0.0" # This binds to all host interfaces, including 192.168.50.61
  #   protocol: TCP
  # - containerPort: 443
  #   hostPort: 443
  #   listenAddress: "0.0.0.0"
  #   protocol: TCP
  kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            # Taint the control plane node to prevent workload scheduling
            register-with-taints: "node-role.kubernetes.io/control-plane=:NoSchedule"
            cloud-provider: "external"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=true"